### PR TITLE
Support `password_challenge`

### LINKED ISSUE #21: Support `authenticate: password_challenge`
A little while back I created a [PR for for authentication-zero](https://github.com/rails/rails/pull/43688) to support the [upcoming feature in Rails 7.1](https://github.com/rails/rails/pull/43688) that allows you to provide a `password_challenge` param directly to the `authenticate` method call.

I'd be happy to submit a PR if you're interested in supporting it in this project.

### PR DESCRIPTION
**Pull request by kylekeesling**
Support the [Rails 7.1 feature](https://github.com/rails/rails/pull/43688) that allows you to provide a `password_challenge` param directly to the `authenticate` method call.

Closes #21

### CODE REVIEW

**Comment by kylekeesling** [comment]
I've never created a backport before but if you can point me in the right direction I'm happy to take a crack at it!

**Comment by excid3** [comment]
I think when the Rails engine / gem loads, we can check the Rails version. If it's < 7.0, we can require the file that patches Rails with the features.

**Comment by excid3** [comment]
Alrighty, I extracted a Backports module that you should be able to add this to.

https://github.com/excid3/revise_auth/blob/main/lib/revise_auth/backports.rb

**Comment by kylekeesling** [comment]
My first thought is that since `password_challenge` extends existing `secure_password` functionality that we may actually need to monkey patch this.

Here's the bulk of the new verification code that was added to make it work:
https://github.com/rails/rails/pull/43688/files#diff-eb95a603176c0d3f5d51367a73239f862ca62be7caa2b4144bcda6370bc838afR104

Let me know if you think this is the right path, and if so I've not done a lot of monkey patching, so any suggestions on how to roll that into `Backports` would be very helpful 🙈

**Comment by kylekeesling** [comment]
I screwed up pulling in the changes on this PR, so rather than fighting with git I'm going to close and reopen a fresh branch

**Pull request closed without merging**
