### PR TITLE
Backport `authenticate_by` to prevent timing-attacks.

### PR DESCRIPTION
**Pull request by dixpac**
Backport `authenticate_by` to prevent timing-attacks.
https://github.com/rails/rails/blob/main/activerecord/lib/active_record/secure_password.rb#L41.

Skipped tests, but if you want I can write the tests also :)

### CODE REVIEW

**Comment by excid3** [comment]
Hah, you beat me to it!

Should we only include this if the method doesn't already exist?

**Comment by dixpac** [comment]
Yup, I agree. If you already done it, just close my PR np :)
If not I can do it :)

**Comment by excid3** [comment]
I haven't done it yet, so go for it. 👍 

Makes me also want to backport the other authentication modules that Jonathan has been working on in 7.1. Should we do all of them and just use the new goodness everywhere?

**Comment by excid3** [comment]
I extracted into a `Backports` module so we can stash all the Rails 7.1 stuff in there and only include it for <= 7.0.

**Pull request merged**
