### PR TITLE
Signed session cookie instead of plain session cookie.

### PR DESCRIPTION
**Pull request by dixpac**

### CODE REVIEW

**Comment by dixpac** [comment]
Maybe `signed cookie` would be healthier approach, wdyt?

**Comment by excid3** [comment]
What's the tradeoffs? I thought the session was encrypted and typically used for this situation.

**Comment by dixpac** [comment]
As far sa I know, session is encrypted but it is not signed. So it can't be read from, but it can be tampered with.
While signed cookie can't be tampered with because it is signed.

Also, I remember seeing old DHHs video where he shown theirs authentication process, and they were also using signed cookie. (https://youtu.be/lEUkarkROv0?t=465 - LOC 11 on the video 😄  )

**Comment by excid3** [comment]
If it's encrypted, it wouldn't be tamperable since it's encrypted with the secret_key_base.
I think the only difference is the signed cookie can be decoded and you can read the contents client side, but the encrypted one cannot. 

Maybe there's value to that since I know that Basecamp and I have both used the current user ID on the client side with Javascript.

**Comment by bdewater** [comment]
> As far sa I know, session is encrypted but it is not signed.

That's not correct: https://guides.rubyonrails.org/configuring.html#config-action-dispatch-use-authenticated-cookie-encryption - Rails uses `ActiveSupport::MessageEncryptor` here that has always supported authenticated encryption.

Using encryption without authentication (i.e. AES-CBC without the SHA1 HMAC) can lead to decryption: https://cybergibbons.com/reverse-engineering-2/why-is-unauthenticated-encryption-insecure/

**Comment by dixpac** [comment]
After researching more you are both correct, thanks ❤️

Only benefit with `signed cookie` would be that user would stayed logged in after closing the browser.
But, same can be implemented with `remember_me` cookie which is maybe a better choice for this engine.

So I'm closing this 😀

**Comment by kaspth** [comment]
> Only benefit with `signed cookie` would be that user would stayed logged in after closing the browser.

@dixpac I'm curious about this and don't understand, how would a `signed cookie` keep a user signed in versus the `session`?

**Pull request closed without merging**
